apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIxMTIxMjE0NTk1NloXDTMxMTIxMTE0NTk1NlowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKX+
    D2wTVpOT50t1ozo4w8WEg5MMNfN9cW8iWKDZf551IfvE1tz1PNBTUobWMbSR3pai
    k7GJsyKul2bnUd3liDl/JZDi6sSxdR1K2eYnwJu9Z7AUJ5UlNjsa8IOcmPuDm9YM
    XedA4QmoxsrTWxZ5hnLr977Gl2mvv1ah1edtggbJFLFTzNJTuXVhgePzZme4es/a
    WIPvxjOeGhJMcHhx6rcIiycWsX9yEAnFiLMvFRb+5N6rsbRK4dkqk1wJOFw3AjwA
    WQ8knMoSGgjgi4RuT51XYm4kXHf0/Ffq5MHqXyWcUXTUttzUsoqHriim2p6lHnk9
    kZ2/7KvZ+EJk0Mb/Qq8CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBRXcVPxqMy/uUmwu1nLEOWQnJ7eVjANBgkqhkiG9w0BAQsFAAOCAQEAa4u50YZj
    i6myuy6c8PDeqnCd+mPCBrjvZ6mr1E7DHlnanj+zUdt5kyBJxzYESF/z+gvmPS/I
    iDGK2n7tpCD77p1S5Mf/1g3cc/VrV8kkeGywJ3SwY1np8HpVqe5n4gvK6d7ooMAU
    W721GRJ+GKOGTvtW09xeo60iAS9jyQqzo5YmVpOVwO4zUbBMa9pXTp5u/T7gxj0v
    +NJu0ahC9Pg06cCovS5j8ctZqvW9L1NRg7RA/hwwTQOm4haywyAxOXPQeQbtlf+k
    6T6QbwKMaej+CY9MN6zbtzvdtjiSbEmZnIfwJ7MoLoc9EIJlTYLI0j9vZSaBDF9v
    TA6XAFJUUzmnag==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-12-13T19:26:45Z"
  name: kube-root-ca.crt
  namespace: guestbook
