apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1USXhNakUwTlRrMU5sb1hEVE14TVRJeE1URTBOVGsxTmxvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1grCkQyd1RWcE9UNTB0MW96bzR3OFdFZzVNTU5mTjljVzhpV0tEWmY1NTFJZnZFMXR6MVBOQlRVb2JXTWJTUjNwYWkKazdHSnN5S3VsMmJuVWQzbGlEbC9KWkRpNnNTeGRSMUsyZVlud0p1OVo3QVVKNVVsTmpzYThJT2NtUHVEbTlZTQpYZWRBNFFtb3hzclRXeFo1aG5Mcjk3N0dsMm12djFhaDFlZHRnZ2JKRkxGVHpOSlR1WFZoZ2VQelptZTRlcy9hCldJUHZ4ak9lR2hKTWNIaHg2cmNJaXljV3NYOXlFQW5GaUxNdkZSYis1TjZyc2JSSzRka3FrMXdKT0Z3M0Fqd0EKV1E4a25Nb1NHZ2pnaTRSdVQ1MVhZbTRrWEhmMC9GZnE1TUhxWHlXY1VYVFV0dHpVc29xSHJpaW0ycDZsSG5rOQprWjIvN0t2WitFSmswTWIvUXE4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSWGNWUHhxTXkvdVVtd3UxbkxFT1dRbko3ZVZqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFhNHU1MFlaagppNm15dXk2YzhQRGVxbkNkK21QQ0JyanZaNm1yMUU3REhsbmFuait6VWR0NWt5Qkp4ellFU0Yveitndm1QUy9JCmlER0sybjd0cENENzdwMVM1TWYvMWczY2MvVnJWOGtrZUd5d0ozU3dZMW5wOEhwVnFlNW40Z3ZLNmQ3b29NQVUKVzcyMUdSSitHS09HVHZ0VzA5eGVvNjBpQVM5anlRcXpvNVltVnBPVndPNHpVYkJNYTlwWFRwNXUvVDdneGowdgorTkp1MGFoQzlQZzA2Y0NvdlM1ajhjdFpxdlc5TDFOUmc3UkEvaHd3VFFPbTRoYXl3eUF4T1hQUWVRYnRsZitrCjZUNlFid0tNYWVqK0NZOU1ONnpidHp2ZHRqaVNiRW1abklmd0o3TW9Mb2M5RUlKbFRZTEkwajl2WlNhQkRGOXYKVEE2WEFGSlVVem1uYWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklsSXpYME5CVDJONmFXWk9YMlpqY0ZRemJrOURjVGhFZDA5WldHWXhlVTA1YUU1TWQwNW9aMGN3Ukc4aWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMXFhamM0TWlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pWXpjelltTmhaVGN0TXpkaVlpMDBNemd4TFRobE1qSXRZbVV5TWpBM05EazNaRFkySWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5aSFM3SVliRE8wUHVxYlBYSFNXTkhwcjd3NWpnZmhPM24zN0MtQ1JoY1ZCb3FqZFltXzM2ang0ZHAxQU9YOG1ZcFE5R29OUmxraU9ua0JCdW1xVF84dXo3a21PeVNnWmhDUWRjRERBeE5nQkQwVjNkelhGTjUtaElwM3dMNnJtOFhjQ21kTWxwNkxJSlpUZzVJeXJwYWlwTzlBVml5WU4xNHRZQ00tQlNQWkJ3RDNRTTVxUXFDYnRXdWUtQzBQZFF1NlowVUhBeXpLMGllZXBsc2tKY2QwQnFlQWJzVngxLWVOSVp6clpJc09FYTNHTEdEb0lQWWdYVG8tTjN4dmRaUFhOTFEwTG9VRVJqT3h0SmtOYThNdzNxLXBGRFBHTW9FX0JrLURlRFQxVGNvZ3kxUmpSZF9DVll0VzVCTEtfdnNkOFdKTm5zVXB6cUNPWlJsRlUxUmc=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: c73bcae7-37bb-4381-8e22-be2207497d66
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-12-13T19:26:45Z"
  name: default-token-jj782
  namespace: guestbook
type: kubernetes.io/service-account-token
